os: osx
osx_image: xcode10.2
language: objective-c
cache: cocoapods
podfile: $TRAVIS_BUILD_DIR/Podfile
xcode_project: XyBleSdk.xcworkspace
xcode_scheme: XyBleSdk iOS
xcode_destination: platform=iOS Simulator,OS=11.0,name=iPhone X
script:
  ./scripts/build.sh
deploy:
    provider: script
    script:
      ./scripts/deploy.sh
    on:
      branch: master
      tags: true
