os: osx
osx_image: xcode11
language: objective-c
cache: cocoapods
podfile: $TRAVIS_BUILD_DIR/Podfile
xcode_project: XyBleSdk.xcworkspace
xcode_scheme: XyBleSdk iOS
xcode_destination: platform=iOS Simulator,OS=11.0,name=iPhone X
addons:
  sonarcloud:
    organization: xyo-network