name: Base Build

on: 
  push: 

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=latest,name=iPhone 11']

    steps:
    - uses: actions/checkout@v2
    - name: set up pod and xcpretty
      run: |
        gem install cocoapods
        gem install xcpretty
    - name: clear and prep
      run: | 
          pod deintegrate
    - name: build
      env: 
        destination: ${{ matrix.destination }}
      run: | 
        pod install --project-directory=SampleiOS
        xcodebuild -workspace SampleiOS/SampleiOS.xcworkspace -scheme SampleiOS -destination "${destination}" -UseModernBuildSystem=NO ONLY_ACTIVE_ARCH=NO | xcpretty 