name: pod build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
    run: | 
      pod install
      pod update

    - name: Force xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    
    - name: Clean
      run: xcodebuild clean -UseModernBuildSytem=1 -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS" 

    - name: build
      run: xcodebuild build -UseModernBuildSytem=1 -workspace XyBleSdk.xcworkspace -scheme "XyBleSdk iOS"