name: Swift Build

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        swift package resolve
        swift build -v